### ISSUE TITLE
Resolve lot of errors

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/bazar#2]
```
composer require --dev nunomaduro/larastan orchestra/testbench:^5.5.0
vendor/bin/phpstan analyse
```

`phpstan.neon.dist`

```yaml
includes:
    - vendor/nunomaduro/larastan/extension.neon
parameters:
    level: 5
    checkMissingIterableValueType: false
    paths:
        - src/
        - config/
        - database/
        - routes/
```
